server:
  port: 8001
  servlet:
    context-path: /fanBlog
spring:
  datasource:
    druid:
      url: jdbc:mysql://xxx:3306/blog?connectTimeout=5000&socketTimeout=10000&autoReconnect=true&failOverReadOnly=false&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: xxx
      password: xxx
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: xxx
    port: 6379
    password: xxx
    database: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    local-cache-scope: statement

